### ISSUE TITLE
有固定宽度的子组件（Ellipse）导致 Table.Column 的 width 属性失效

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1588]
## 问题描述

demo: https://codepen.io/Etertops/pen/MxvEGN?editors=0010

**Comment by imsobear** [comment]
https://alibaba.github.io/ice/component/ellipsis#%E7%94%A8%E5%9C%A8%E8%A1%A8%E6%A0%BC%E4%B8%AD

**Comment by youluna** [comment]
```css
table {
  table-layout: fixed;
}

```
