### ISSUE TITLE
[RFC] 通用动态多主题方案

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#4223]
## 背景

- Dark Mode 未来会成为标配
- 项目里使用样式变量需要有规范
- 目前 ice 研发框架对于 `@alifd/next` 组件体系，通过 theme 主题文件的方式支持[多主题切换](https://ice.work/docs/guide/advance/fusion#%E5%8A%A8%E6%80%81%E5%88%87%E6%8D%A2%E4%B8%BB%E9%A2%98)。而针对其他组件体系，比如 `antd`  没有一个通用的解决方案指导开发者进行多主题方案的开发。

### 目录约定

项目目录下增加 `src/themes` 文件夹：

```
|- src/
|   |- themes/
|   |   |- light.css
|   |   |- dark.css
```

主题变量统一通过 css vars 定义。

### 定义主题变量

如果使用 fusion 组件，通过主题包引入变量：

```less
// 通过 fusion 主题包引入 css vars
@import '~/@alifd/theme-1/variables.css';

:root {
  // 允许扩展额外的变量
  --custom-color: #FFF0E6;
}
```

如果使用 antd 组件，则直接定义对应的变量：

```less
:root {
  // 对应 antd less 里的 @primary-color
  --primary-color: #f40;
  --link-color: #f50;

  --custom-color: #FFF0E6;
}
```

同时为了让业务代码使用变量更加统一（不需要区分 antd/fusion/...）和简单（fusion 的变量太多记不住），因此我们会根据定义的 antd/fusion 变量自动推导出框架内置变量（开发者也可以自己定义），比如 `--ice-primary-color`, `--ice-link-color`，然后业务代码里就可以使用这些变量了。

### 使用主题变量

CSS:

```less
// components/List/index.module.css
.container {
   color: var(--ice-primary-color);
   background-color: var(--custom-color);
}
```

Less/Sass:

```scss
// components/List/index.module.scss
.container {
   border-color: var(--ice-primary-color);

   // 也可以直接使用 less/scss 变量（跟 antd/fusion 里的代码一样），不过最好是推荐上面这种直接用 css vars 的方式
   color: $ice-primary-color;
   background-color: $ice-primary-color;
}
```

### 主题切换

全局包裹 Provider：

```tsx
// src/app.tsx
import { ThemeProvider, runApp } from 'ice';

runApp({
  app: {
    addProvider: (children) => {
      return <ThemeProvider value='light'>{children}</ThemeProvider>;
    }
  }
})
```

使用/切换主题：

```tsx
// src/layouts/BasicLayout/index.tsx
import { useTheme } from 'ice';

export default function BasicLayout() {
  const [theme, setTheme] = useTheme();
}
```

### 自动注入全局 Less/Sass 变量并赋值为 CSS Vars

比如如果项目使用了 antd，会在编译时对所有 less 文件注入以下变量：

```less
@primary-color: var(--primary-color);
// ...
```

这样使用 `@primary-color` 的地方都会变为 css vars。

### CSS 变量不支持 Less/Sass 的 lighten 之类的方法

按照上述操作之后，会出现下面这种情况：

```less
@primary-color: vars(--primary-color);
@draken-color: lighten(@primary-color, 20%);
```

这在 less 编译时会直接抛错，因此针对这种场景需要前置的将 lighten() 结果算出来，然后到 less 编译的阶段这里已经是具体的色值了。

css variables 并不能完整支持预编译语法中的计算逻辑，为了样式切换时正确渲染内容，需要对参与计算的变量提前编译，比如：

```less
@draken-color: lighten(@white-color, 20%);
```

// 对于上述变量，将会采取预先编译结果的方式，先获取编译后的值，再转化为 css 变量

```css
@draken-color: #aaa;
```

> 对于 @alifd/next 主题，参与计算的变量会通过 $color-calculate- 前缀标识，而对于 antd 以及其他第三方组件，内部需要维护一个需要预先计算的列表
> 优化方案：可以通过 css ast 结构分析，自动获取需要提前编译的参数，需要评估 ast 解析性能及成本

**Comment by fengxs269** [comment]
诉求场景：子应用可通过css前缀做样式隔离后通过主应用定义css变量的方式来支持子应用接入到主应用时的样式统一
提议：
 1. 使用css-variable时也能支持css-prefix的方式
 2. 应用的默认主题变量请不要生成：root下的变量，而是请放在var的第二位默认值，例如:
 ```css
.next-tag{
   color:  var(--brand-color, #000000)
}
```

**Comment by FuzzyFade** [comment]
> ## 背景
> * Dark Mode 未来会成为标配
> * 项目里使用样式变量需要有规范
> * 目前 ice 研发框架对于 `@alifd/next` 组件体系，通过 theme 主题文件的方式支持[多主题切换](https://ice.work/docs/guide/advance/fusion#%E5%8A%A8%E6%80%81%E5%88%87%E6%8D%A2%E4%B8%BB%E9%A2%98)。而针对其他组件体系，比如 `antd`  没有一个通用的解决方案指导开发者进行多主题方案的开发。
> 
> ## 方案介绍
> ### 目录约定
> 项目目录下增加 `src/themes` 文件夹：
> 
> ```
> |- src/
> |   |- themes/
> |   |   |- light.css
> |   |   |- dark.css
> ```
> 
> 主题变量统一通过 css vars 定义。
> 
> ### 定义主题变量
> 如果使用 fusion 组件，通过主题包引入变量：
> 
> ```css-less
> // 通过 fusion 主题包引入 css vars
> @import '~/@alifd/theme-1/variables.css';
> 
> :root {
>   // 允许扩展额外的变量
>   --custom-color: #FFF0E6;
> }
> ```
> 
> 如果使用 antd 组件，则直接定义对应的变量：
> 
> ```css-less
> :root {
>   // 对应 antd less 里的 @primary-color
>   --primary-color: #f40;
>   --link-color: #f50;
> 
>   --custom-color: #FFF0E6;
> }
> ```
> 
> 同时为了让业务代码使用变量更加统一（不需要区分 antd/fusion/...）和简单（fusion 的变量太多记不住），因此我们会根据定义的 antd/fusion 变量自动推导出框架内置变量（开发者也可以自己定义），比如 `--ice-primary-color`, `--ice-link-color`，然后业务代码里就可以使用这些变量了。
> 
> ### 使用主题变量
> CSS:
> 
> ```css-less
> // components/List/index.module.css
> .container {
>    color: var(--ice-primary-color);
>    background-color: var(--custom-color);
> }
> ```
> 
> Less/Sass:
> 
> ```css-scss
> // components/List/index.module.scss
> .container {
>    border-color: var(--ice-primary-color);
> 
>    // 也可以直接使用 less/scss 变量（跟 antd/fusion 里的代码一样），不过最好是推荐上面这种直接用 css vars 的方式
>    color: $ice-primary-color;
>    background-color: $ice-primary-color;
> }
> ```
> 
> ### 主题切换
> 全局包裹 Provider：
> 
> ```tsx
> // src/app.tsx
> import { ThemeProvider, runApp } from 'ice';
> 
> runApp({
>   app: {
>     addProvider: (children) => {
>       return <ThemeProvider value='light'>{children}</ThemeProvider>;
>     }
>   }
> })
> ```
> 
> 使用/切换主题：
> 
> ```tsx
> // src/layouts/BasicLayout/index.tsx
> import { useTheme } from 'ice';
> 
> export default function BasicLayout() {
>   const [theme, setTheme] = useTheme();
> }
> ```
> 
> ## 实现思路
> ### 自动注入全局 Less/Sass 变量并赋值为 CSS Vars
> 比如如果项目使用了 antd，会在编译时对所有 less 文件注入以下变量：
> 
> ```css-less
> @primary-color: var(--primary-color);
> // ...
> ```
> 
> 这样使用 `@primary-color` 的地方都会变为 css vars。
> 
> ### CSS 变量不支持 Less/Sass 的 lighten 之类的方法
> 按照上述操作之后，会出现下面这种情况：
> 
> ```css-less
> @primary-color: vars(--primary-color);
> @draken-color: lighten(@primary-color, 20%);
> ```
> 
> 这在 less 编译时会直接抛错，因此针对这种场景需要前置的将 lighten() 结果算出来，然后到 less 编译的阶段这里已经是具体的色值了，方案参考主 issue。

问题 1 : 对于类似 material-ui 那种的 jss 样式方案该怎么做。
问题 2 : 
```typescript
runApp({
  app: {
    addProvider: (children) => {
      return <ThemeProvider value='light'>{children}</ThemeProvider>;
    }
  }
})
```

`ThemeProvider` 不应有 `value props`，因为在配置文件中已经设置好了 `default: true`

**Comment by imsobear** [comment]
如何声明默认主题？约定的话就 `themes/default.css` 对应到 js 里就是 `default` ？

**Comment by imsobear** [comment]
- ThemeProvider 自动包裹，这个我觉得 OK
- material-ui 是 style in js，那就需要根据 css vars 再推导出 js 变量，然后封装一个 plugin-material-ui，主要是响应框架的 ThemeProvider 然后作用给 material-ui 自己的 ThemeProvider

@FuzzyFade

**Comment by youluna** [comment]
1. 为了方便开发者使用，给两个体系的现有变量取别名没什么问题，保证原来的变量仍然可用就行。
2. 再明确下 `@alifd/next` 组件体系下的多主题切换方案：
- a. 「ice旧有方案」ice在工程上把sass变量编译成css变量
- b. 「新方案」直接采用主题包编译出来的css变量

建议采用 `b` 方案，可以省掉很多sass处理过程，不过需要注意`@alifd/theme-1/variables.css`文件是带着作用范围`:root: {}`的。

**Comment by FuzzyFade** [comment]
关于CSS 变量不支持 Less/Sass 的 lighten 之类的方法的问题：
```less
@primary-color: vars(--primary-color);
@draken-color: lighten(@primary-color, 20%);
```
类似于这种在变量中使用函数，则可以在主题文件里定义好变量 (@draken-color) 即可。（似乎并不需要提前计算列表)

而类似于下面这种：
```less
@primary-color: vars(--primary-color);
.foo {
  color: lighten(@primary-color, 20%);
}
```

则需要先转为（hash 后面的序号是递增的，且如果遇到 value str 相同的，则使用相同的变量）
```less
@primary-color: vars(--primary-color);
@hash-1: lighten(@primary-color, 20%);

.foo {
  color: @hash-1;
}
```

最后定义时则定义好 hash-1 即可

**Comment by imsobear** [comment]
`themes/dark.css`：

```css
@import '~@alifd/fusion-theme-dark/variables.css';

:root {
  --ice-color: #f40;
}
```

`themes/light.css`：

```css
@import '~@alifd/fusion-theme-light/variables.css';

:root {
  --ice-color: #555;
}
```

`src/global.css`：

```css
@import './themes/dark.css?scope=dark';
@import './themes/light.css?scope=light';

@import '~@alifd/next/dist/next.var.css';

@import '~/antd/dist/antd.css?scope=light';
@import '~/antd/dist/antd.dark.css?scope=dark';
```
