### ISSUE TITLE
vite模式下cssModule不支持嵌套写法，webpack可以

### ISSUE THREAD

**Issue by CX330-jiuxi** [alibaba/ice#5333]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
提供下具体的写法

**Comment by CX330-jiuxi** [comment]
```css
.container {
  width: 100vw;
  height: 100vh;
  display: flex;
  flex-direction: column;

  .header {
    flex: 0 0 auto;
  }

  .content {
    flex: 1 1 auto;
    background: #444;
  }
}


```

**Comment by CX330-jiuxi** [comment]
@ClarkXia 
```css
.container {
  width: 100vw;
  height: 100vh;
  display: flex;
  flex-direction: column;

  .header {
    flex: 0 0 auto;
  }

  .content {
    flex: 1 1 auto;
    background: #444;
  }
}
```

<img width="640" alt="image" src="https://user-images.githubusercontent.com/51979013/170654281-b77282da-d6b7-435e-a818-71bf7e6b4a38.png">
